# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fce3ad87-9cad-41f7-8f0d-a0813ff80f0d";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6EE2-E98D";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/6EE2-B8E0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fce3ad87-9cad-41f7-8f0d-a0813ff80f0d";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/fce3ad87-9cad-41f7-8f0d-a0813ff80f0d";
      fsType = "btrfs";
      options = [ "subvol=@opt" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/fce3ad87-9cad-41f7-8f0d-a0813ff80f0d";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/fce3ad87-9cad-41f7-8f0d-a0813ff80f0d";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/fce3ad87-9cad-41f7-8f0d-a0813ff80f0d";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/fce3ad87-9cad-41f7-8f0d-a0813ff80f0d";
      fsType = "btrfs";
      options = [ "subvol=@var_log" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/66a6b46f-5680-452f-8281-4a5374ee9510"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
